### ISSUE TITLE
Error when no profiles are defined in the conf file

### ISSUE THREAD

**Issue by ypoluektovich** [Cobliteam/cassandra-migrate#15]
As of version 0.2.3, if no profiles are defined in the main configuration file, the program crashes when trying to read the config:
```
$ cassandra-migrate -c migrations.yaml migrate
Traceback (most recent call last):
  File "/path_redacted/venv/bin/cassandra-migrate", line 18, in <module>
    main()
  File "/path_redacted/venv/lib/python3.6/site-packages/cassandra_migrate/cli.py", line 90, in main
    config = MigrationConfig.load(opts.config_file)
  File "/path_redacted/venv/lib/python3.6/site-packages/cassandra_migrate/config.py", line 90, in load
    return cls(config, os.path.dirname(path))
  File "/path_redacted/venv/lib/python3.6/site-packages/cassandra_migrate/config.py", line 60, in __init__
    profiles = _assert_type(data, 'profiles', dict)
  File "/path_redacted/venv/lib/python3.6/site-packages/cassandra_migrate/config.py", line 26, in _assert_type
    key, tpe, type(value)))
ValueError: Config error: profiles: expected <class 'dict'>, found <class 'NoneType'>
```

**Comment by danielkza** [comment]
Should be fixed by 0.2.4, which I just uploaded to PyPI. Thanks for the report!
