### ISSUE TITLE
Error when no profiles are defined in the conf file, pt. 2

### ISSUE THREAD

**Issue by ypoluektovich** [Cobliteam/cassandra-migrate#17]
Hi, it's me again :)
With v0.2.4 I get this:
```
INFO:Migrator:Dropping existing keyspace 'dqw'
INFO:Migrator:Creating keyspace 'dqw'
Traceback (most recent call last):
  File "/path_redacted/venv/bin/cassandra-migrate", line 18, in <module>
    main()
  File "/path_redacted/venv/lib/python3.6/site-packages/cassandra_migrate/cli.py", line 109, in main
    cmd_method(opts)
  File "/path_redacted/venv/lib/python3.6/site-packages/cassandra_migrate/migrator.py", line 480, in reset
    self.migrate(opts)
  File "/path_redacted/venv/lib/python3.6/site-packages/cassandra_migrate/migrator.py", line 459, in migrate
    self._ensure_keyspace()
  File "/path_redacted/venv/lib/python3.6/site-packages/cassandra_migrate/migrator.py", line 217, in _ensure_keyspace
    durable_writes=cassandra_ddl_repr(profile['durable_writes'])))
KeyError: 'durable_writes'
```

To clarify, the migrations file looks like this:
```
keyspace: dqw
migrations_path: ./migrations
```
If I add the default dev profile explicitly, it all works.

**Comment by danielkza** [comment]
Fixed by 29576e2db92e3dd66f5d6dfedf2fe767eece1d4f. Thanks!
