### ISSUE TITLE
Cannot generate migrations without specifying new_migration_name

### ISSUE THREAD

**Issue by revolaution** [Cobliteam/cassandra-migrate#7]
As of version 0.2.1, we cannot run the `cassandra-migrate generate` command without defining a new_migration_name in the config file. 
While this is not a major issue, and the workaround is pretty simple, the Readme does imply that there is a default value, which is inconsistent with the behavior. 

```
Traceback (most recent call last):
  File "/usr/local/bin/cassandra-migrate", line 18, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/cassandra_migrate/cli.py", line 84, in main
    new_path = Migration.generate(config=config, description=opts.description)
  File "/usr/local/lib/python2.7/site-packages/cassandra_migrate/migration.py", line 86, in generate
    fname = fname_fmt.format(**format_args) + '.cql'
KeyError: u'description'
```

**Comment by danielkza** [comment]
There is actually a mistake in the default value. I'll release 0.2.2 with a fix right away. Thank you!
